name:        randy.secrist.io >

root:        /

future:      true
safe:        false
lsi:         false
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false

permalink:   /:year/:month/:day/:title/
paginate:    5
recent_posts: 10
plugins: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, README.md]
